services:
  db:
    image: postgres:15-alpine
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  
  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    ports:
      - '8000:8000'
    depends_on:
      - db
      - rabbit
    volumes:
      - .:/app
  
  rabbit:
    image: rabbitmq:3-management
    ports:
      - '15672:15672'
      - '5672:5672'