[pytest]
pythonpath = .
testpaths = tests
addopts = -ra --tb=short --strict-markers --cov=root --cov-config=.coveragerc --cov-report=term-missing --cov-report=html:htmlcov --cov-report=xml:coverage.xml
