"""add_currency_in_books

Revision ID: 380033311671
Revises: 4663f2a5ac64
Create Date: 2026-04-08 17:21:21.619554

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "380033311671"
down_revision: Union[str, Sequence[str], None] = "4663f2a5ac64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("currency", sa.String(length=3), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("books", "currency")
    # ### end Alembic commands ###
