"""init unified schema

Revision ID: aeae7ecd1647
Revises: 
Create Date: 2026-04-16 17:10:53.202952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aeae7ecd1647'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=256), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_events_idempotency_key'), 'ingestion_events', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_ingestion_events_stage'), 'ingestion_events', ['stage'], unique=False)
    op.create_table('listing_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=256), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('listing_id', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('last_seen_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('content_hash_light', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_state_idempotency_key'), 'listing_state', ['idempotency_key'], unique=True)
    op.create_table('listing_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=256), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description_markdown', sa.Text(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_versions_content_hash'), 'listing_versions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_listing_versions_idempotency_key'), 'listing_versions', ['idempotency_key'], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_url'), 'listings', ['url'], unique=True)
    op.create_table('target_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_target_urls_last_scraped_at'), 'target_urls', ['last_scraped_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_target_urls_last_scraped_at'), table_name='target_urls')
    op.drop_table('target_urls')
    op.drop_index(op.f('ix_listings_url'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_listing_versions_idempotency_key'), table_name='listing_versions')
    op.drop_index(op.f('ix_listing_versions_content_hash'), table_name='listing_versions')
    op.drop_table('listing_versions')
    op.drop_index(op.f('ix_listing_state_idempotency_key'), table_name='listing_state')
    op.drop_table('listing_state')
    op.drop_index(op.f('ix_ingestion_events_stage'), table_name='ingestion_events')
    op.drop_index(op.f('ix_ingestion_events_idempotency_key'), table_name='ingestion_events')
    op.drop_table('ingestion_events')
    # ### end Alembic commands ###
